<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>{{ config('app.name', 'NOVA SHOP') }}</title><meta name="description" content="فروشگاه آنلاین مدرن و سریع">
@vite(['resources/css/app.css','resources/js/app.js'])
</head>
<body>
<div class="topbar"><div class="container topbar-inner"><span>ارسال رایگان برای سفارش‌های بالای ۲ میلیون تومان</span><span>پشتیبانی ۹ تا ۲۱ • پرداخت امن و سریع</span></div></div>
<header class="navbar"><div class="container nav-inner">
<a class="brand" href="#home"><span class="brand-mark" aria-hidden="true">N</span><span>NOVA SHOP</span></a>
<nav class="nav-links" aria-label="منوی اصلی"><a href="#home">خانه</a><a href="#categories">دسته‌بندی‌ها</a><a href="#products">محصولات</a><a href="#services">مزایای خرید</a></nav>
<div class="actions"><button class="icon-btn" type="button" data-search aria-label="جستجو"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg></button><div class="relative"><button class="icon-btn" type="button" aria-label="سبد خرید"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M6 8h12l1 12H5L6 8Z"/><path d="M9 8a3 3 0 0 1 6 0"/></svg></button><span class="cart-count" data-cart-count>۰</span></div></div>
</div></header>
<main id="home">
<section class="hero"><div class="container hero-shell"><div class="hero-grid"><div class="hero-copy"><span class="eyebrow">● کالکشن جدید ۱۴۰۵</span><h1>خریدی ساده، شیک و دقیقاً برای شما.</h1><p>محصولات منتخب روزمره، دیجیتال و سبک زندگی را با تجربه‌ای سریع، مرتب و بدون حواس‌پرتی پیدا کنید.</p><div class="cta-row"><a class="btn btn-primary" href="#products">مشاهده محصولات</a><a class="btn btn-secondary" href="#categories">کشف دسته‌بندی‌ها</a></div></div><div class="hero-art" aria-label="پیش‌نمایش فروشگاه"><span class="blob blob-a"></span><span class="blob blob-b"></span><div class="device"><div class="device-screen"><div class="screen-header"><strong style="font-size:13px">انتخاب‌های امروز</strong><span class="screen-chip">پرفروش</span></div><div class="mock-products"><div class="mock-card"><div class="mock-img"></div><div class="mock-line"></div><div class="mock-price"></div></div><div class="mock-card"><div class="mock-img"></div><div class="mock-line" style="width:70%"></div><div class="mock-price"></div></div><div class="mock-card"><div class="mock-img"></div><div class="mock-line" style="width:58%"></div><div class="mock-price"></div></div><div class="mock-card"><div class="mock-img"></div><div class="mock-line"></div><div class="mock-price"></div></div></div></div></div></div></div></section>
<section class="section" id="categories"><div class="container"><div class="section-head"><div><h2>دسته‌بندی‌های محبوب</h2><p>هر چیزی که لازم داری، در چند قدم ساده.</p></div><a class="link-more" href="#products">همه محصولات ←</a></div><div class="categories">
<a class="category" href="#products"><div class="category-icon">◫</div><b>مد و پوشاک</b><span>۲۴۰ محصول</span></a><a class="category" href="#products"><div class="category-icon">▣</div><b>دیجیتال</b><span>۱۱۸ محصول</span></a><a class="category" href="#products"><div class="category-icon">⌂</div><b>خانه و زندگی</b><span>۱۸۶ محصول</span></a><a class="category" href="#products"><div class="category-icon">◯</div><b>زیبایی و سلامت</b><span>۹۴ محصول</span></a><a class="category" href="#products"><div class="category-icon">◇</div><b>لوازم کاربردی</b><span>۱۵۲ محصول</span></a>
</div></div></section>
<section class="section" id="products"><div class="container"><div class="section-head"><div><h2>محصولات منتخب</h2><p>پرفروش‌ترین انتخاب‌های این هفته.</p></div><input data-search-input aria-label="جستجوی محصول" placeholder="جستجوی محصول..." style="width:220px;max-width:45vw;height:42px;border:1px solid #cbd5e1;border-radius:12px;padding:0 13px;background:#fff;outline:none"></div>
@php $products=[['p1','هدفون بی‌سیم نویزکنسلینگ','صدای شفاف • باتری ۳۰ ساعت',3490000,3990000,'پرفروش'],['p2','ساعت هوشمند مینیمال','نمایشگر AMOLED • ضدآب',2890000,3290000,'جدید'],['p3','کوله‌پشتی شهری پریمیوم','پارچه مقاوم • لپ‌تاپ ۱۵ اینچ',1790000,2190000,'تخفیف'],['p4','چراغ رومیزی هوشمند','نور قابل تنظیم • USB-C',1250000,1490000,'محبوب'],['p5','کیف دستی روزمره','چرم گیاهی • طراحی سبک',1590000,1890000,'جدید'],['p6','اسپیکر قابل حمل','صدای ۳۶۰ درجه • ۱۲ ساعت پخش',2190000,2490000,'پرفروش'],['p7','کیبورد بی‌سیم کم‌حجم','اتصال چندگانه • تایپ نرم',1980000,2290000,'تخفیف'],['p8','ماگ حرارتی استیل','نگهداری دما • درب ضدنشت',790000,950000,'محبوب']]; @endphp
<div class="products">@foreach($products as $product)<article class="product" data-product><div class="product-media"><span class="product-badge">{{ $product[5] }}</span><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.1"><rect x="5" y="5" width="14" height="14" rx="3"/><path d="M8 15l2.8-3.2 2.2 2.3 1.5-1.6L18 16M9 9h.01"/></svg></div><div class="product-body"><div class="rating">★★★★★ <span style="color:#94a3b8">۴.۸</span></div><h3>{{ $product[1] }}</h3><div class="product-meta">{{ $product[2] }}</div><div class="price-row"><div class="price">{{ number_format($product[3]) }} <span style="font-size:10px;font-weight:600">تومان</span><span class="old-price">{{ number_format($product[4]) }}</span></div><button class="add-btn" type="button" data-add="{{ $product[0] }}" data-title="{{ $product[1] }}" data-price="{{ $product[3] }}" aria-label="افزودن {{ $product[1] }} به سبد خرید">+</button></div></div></article>@endforeach</div></div></section>
<section class="container promo"><div class="promo-inner"><div><h3>برای خرید اول، ۱۰٪ تخفیف</h3><p>کد تخفیف را هنگام پرداخت وارد کنید و اولین سفارش‌تان را ارزان‌تر تحویل بگیرید.</p></div><div class="promo-code">NOVAFIRST10</div></div></section>
<section class="section" id="services"><div class="container features"><div class="feature"><div class="feature-icon">↝</div><div><h4>ارسال سریع</h4><p>سفارش‌ها با بسته‌بندی مرتب و رهگیری آسان ارسال می‌شوند.</p></div></div><div class="feature"><div class="feature-icon">✓</div><div><h4>پرداخت امن</h4><p>فرآیند پرداخت شفاف، ساده و آماده اتصال به درگاه واقعی.</p></div></div><div class="feature"><div class="feature-icon">?</div><div><h4>پشتیبانی واقعی</h4><p>پاسخ‌گویی در ساعات کاری برای سوال‌های قبل و بعد از خرید.</p></div></div></div></section>
</main>
<footer class="footer"><div class="container footer-inner"><div><div class="footer-brand">NOVA SHOP</div><p>یک تجربه فروشگاهی مدرن و مینیمال برای خرید روزمره؛ با تمرکز روی سرعت، خوانایی و اعتماد.</p></div><div><h4>دسترسی سریع</h4><a href="#home">خانه</a><br><a href="#categories">دسته‌بندی‌ها</a><br><a href="#products">محصولات</a></div><div><h4>راهنما</h4><a href="#services">مزایای خرید</a><br><a href="#services">پشتیبانی</a><br><a href="#services">شرایط ارسال</a></div><div><h4>سبد خرید</h4><p>تعداد اقلام: <strong data-cart-count>۰</strong></p><p>جمع فعلی: <strong data-cart-total>۰ تومان</strong></p></div></div><div class="container footer-bottom"><span>© ۱۴۰۵ NOVA SHOP</span><span>طراحی رابط بر پایه اصول UI/UX Pro Max</span></div></footer>
<div class="toast" data-toast role="status" aria-live="polite"></div>
</body></html>
