@extends('layouts.store')

@section('content')
<style>
.store-home{background:#fff;color:#17243a;margin-inline:calc((100vw - min(1270px,calc(100% - 34px)))/-2);min-height:100vh;font-family:inherit}.home-wrap{width:min(1160px,calc(100% - 36px));margin:auto}
.notice{height:36px;background:#28a9df;color:#fff;display:flex;align-items:center;justify-content:center;font-size:11px;font-weight:700}.store-header{background:#090b14;color:#fff}.store-header-inner{min-height:72px;display:flex;align-items:center;gap:26px}.brand-main{margin-right:auto;display:flex;align-items:center;gap:10px}.brand-mark{width:34px;height:34px;border-radius:9px;background:#0c8ce8;display:grid;place-items:center;font-weight:900}.brand-text strong{display:block;font-size:14px}.brand-text small{font-size:8px;color:#b5bfcc}.main-menu{display:flex;gap:24px;align-items:center;flex:1;justify-content:center}.main-menu a{font-size:11px;color:#eef2f7}.header-icons{display:flex;gap:10px;align-items:center}.icon-btn{width:32px;height:32px;border:1px solid #2b3040;background:#111522;border-radius:8px;color:#fff;display:grid;place-items:center;font-size:13px}
.hero-area{padding:14px 0}.hero-banner{height:300px;border-radius:9px;overflow:hidden;position:relative;background:#eef4fb}.hero-banner img{width:100%;height:100%;object-fit:cover;display:block}.hero-fallback{height:100%;display:grid;place-items:center;color:#8392a4}.hero-arrow{position:absolute;top:50%;transform:translateY(-50%);width:34px;height:34px;border:0;border-radius:50%;background:#fff;color:#42516b;box-shadow:0 4px 16px #0002}.hero-next{left:14px}.hero-prev{right:14px}
.promo{display:grid;grid-template-columns:180px repeat(5,1fr);gap:9px;margin-top:14px;margin-bottom:34px;background:linear-gradient(135deg,#5d1430,#ad1649);padding:10px;border-radius:9px}.promo-title{display:flex;flex-direction:column;justify-content:center;color:#fff;padding:10px}.promo-title strong{font-size:21px}.promo-title span{font-size:9px;margin-top:5px;opacity:.85}.promo-card{background:#fff;border-radius:8px;padding:8px;color:#24384f}.promo-img{height:82px;background:#f5f7fa;border-radius:6px;display:grid;place-items:center;overflow:hidden}.promo-img img{width:100%;height:100%;object-fit:contain}.promo-name{font-size:10px;font-weight:800;margin-top:7px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.promo-price{font-size:8px;color:#788696;margin-top:4px}
.home-section{margin-bottom:40px}.section-title-row{display:flex;align-items:center;justify-content:space-between;margin-bottom:12px}.section-title-row h2{font-size:17px;margin:0;font-weight:900}.section-title-row a{font-size:10px;color:#3e69f6}.home-products{display:grid;grid-template-columns:repeat(5,1fr);gap:12px}.home-product{background:#fff;border:1px solid #e8edf3;border-radius:11px;padding:11px;position:relative;transition:.2s}.home-product:hover{transform:translateY(-3px);box-shadow:0 14px 30px #24354a12}.home-product-image{height:145px;background:#f5f8fb;border-radius:8px;display:grid;place-items:center;overflow:hidden}.home-product-image img{width:100%;height:100%;object-fit:contain}.home-product h3{font-size:11px;margin:9px 0 5px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.home-product p{font-size:8px;color:#8a97a5;height:27px;line-height:1.6;margin:0;overflow:hidden}.home-price{font-size:10px;font-weight:900;margin-top:7px}.cart-mini{position:absolute;left:10px;bottom:10px;width:27px;height:27px;border-radius:7px;background:#edf7ff;color:#1699e2;display:grid;place-items:center}.blog-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.blog-card{border:1px solid #e7edf3;border-radius:11px;overflow:hidden;background:#fff}.blog-cover{height:120px;background:linear-gradient(135deg,#eef5ff,#dce8ff)}.blog-cover img{width:100%;height:100%;object-fit:cover}.blog-body{padding:12px}.blog-body strong{display:block;font-size:11px}.blog-body p{font-size:9px;color:#8897a6;line-height:1.8;margin:7px 0 0}.footer-modern{background:#0a0d18;color:#fff;margin-top:55px;padding:38px 0 18px}.footer-grid{display:grid;grid-template-columns:1.2fr 1fr 1fr;gap:25px}.footer-modern h3{font-size:14px;margin:0 0 9px}.footer-modern p,.footer-modern a{font-size:9px;color:#b7c0cc;line-height:2;text-decoration:none;display:block}.footer-bottom{text-align:center;border-top:1px solid #202537;margin-top:24px;padding-top:14px;font-size:8px;color:#8893a3}
@media(max-width:900px){.main-menu{display:none}.home-products{grid-template-columns:repeat(3,1fr)}.promo{grid-template-columns:180px repeat(3,1fr);overflow:auto}.footer-grid{grid-template-columns:1fr 1fr}.hero-banner{height:240px}}@media(max-width:600px){.home-wrap{width:calc(100% - 20px)}.notice{font-size:9px}.store-header-inner{min-height:58px}.brand-main{margin-right:0}.header-icons{margin-right:auto}.hero-banner{height:185px}.promo{grid-template-columns:160px repeat(5,135px)}.home-products{grid-template-columns:repeat(2,1fr);gap:8px}.home-product-image{height:120px}.blog-grid{grid-template-columns:1fr}.footer-grid{grid-template-columns:1fr}}
</style>
</head>
<body>
<div class="store-home">
<div class="notice">تحویل سریع اشتراک‌های بین‌المللی با ضمانت فعال‌سازی و پشتیبانی</div>
<header class="store-header"><div class="home-wrap store-header-inner">
<div class="brand-main"><span class="brand-mark">N</span><div class="brand-text"><strong>{{ $siteName }}</strong><small>فروش سریع محصولات دیجیتال</small></div></div>
<nav class="main-menu" aria-label="منوی اصلی"><a href="{{ route('home') }}">صفحه اصلی</a><a href="{{ route('products.index') }}">محصولات</a><a href="#categories">دسته‌بندی‌ها</a><a href="#blog">وبلاگ</a><a href="#about">درباره ما</a><a href="#support">ارتباط با ما</a></nav>
<div class="header-icons"><a class="icon-btn" href="{{ route('cart.index') }}">🛒</a><a class="icon-btn" href="@auth{{ route('account.dashboard') }}@else{{ route('auth') }}@endauth">♙</a></div>
</div></header>
<div class="home-wrap hero-area"><div class="hero-banner" data-home-banner>
@if($bannerSlides->isNotEmpty()) @foreach($bannerSlides as $i=>$slide)<a data-home-slide href="{{ $slide['link'] ?? '#' }}" style="display:{{ $i===0?'block':'none' }};width:100%;height:100%"><img src="{{ $slide['image'] }}" alt="بنر"></a>@endforeach
@if($bannerSlides->count()>1)<button class="hero-arrow hero-prev" type="button">›</button><button class="hero-arrow hero-next" type="button">‹</button>@endif
@else<div class="hero-fallback">برای نمایش بنر، از تنظیمات فروشگاه یک اسلاید اضافه کن.</div>@endif
</div>
<div class="promo"><div class="promo-title"><strong>🔥 پیشنهاد ویژه</strong><span>محصولات محبوب با قیمت مناسب</span></div>
@foreach($allActiveProducts->take(5) as $product)<a class="promo-card" href="{{ route('product.show',$product) }}"><div class="promo-img">@if($product->image)<img src="{{ $product->image }}" alt="{{ $product->name }}" loading="lazy">@else<span>✦</span>@endif</div><div class="promo-name">{{ $product->name }}</div><div class="promo-price">{{ number_format($product->price) }} {{ $product->currency==='IRR'?'تومان':$product->currency }}</div></a>@endforeach</div>
@foreach($categoryProducts as $name=>$items)<section class="home-section" id="categories"><div class="section-title-row"><h2>{{ $name }}</h2><a href="{{ route('products.index',['category'=>$items->first()->category?->slug]) }}">مشاهده همه</a></div><div class="home-products">@foreach($items->take(5) as $product)<a class="home-product" href="{{ route('product.show',$product) }}"><div class="home-product-image">@if($product->image)<img src="{{ $product->image }}" alt="{{ $product->name }}" loading="lazy">@else<span style="font-size:36px;color:#9ba8b7">✦</span>@endif</div><h3>{{ $product->name }}</h3><p>{{ $product->description ?: 'خدمات و محصول دیجیتال با تحویل سریع.' }}</p><div class="home-price">{{ number_format($product->price) }} {{ $product->currency==='IRR'?'تومان':$product->currency }}</div><span class="cart-mini">🛒</span></a>@endforeach</div></section>@endforeach
<section class="home-section" id="blog"><div class="section-title-row"><h2>مطالب وبلاگ</h2><a href="#">مشاهده همه</a></div><div class="blog-grid"><article class="blog-card"><div class="blog-cover"></div><div class="blog-body"><strong>راهنمای خرید سرویس‌های دیجیتال</strong><p>نکات انتخاب اشتراک مناسب و بررسی روش‌های فعال‌سازی.</p></div></article><article class="blog-card"><div class="blog-cover"></div><div class="blog-body"><strong>چگونه سرویس مناسب را انتخاب کنیم؟</strong><p>مقایسه ویژگی‌ها، مدت اشتراک و قیمت قبل از خرید.</p></div></article><article class="blog-card"><div class="blog-cover"></div><div class="blog-body"><strong>خرید امن و پیگیری سفارش</strong><p>سفارش خود را بعد از پرداخت از داخل حساب کاربری دنبال کن.</p></div></article></div></section>
</div>
<footer class="footer-modern" id="about"><div class="home-wrap footer-grid"><div><h3>{{ $siteName }}</h3><p>فروش و تحویل سریع محصولات و سرویس‌های دیجیتال.</p></div><div id="support"><h3>دسترسی سریع</h3><a href="{{ route('products.index') }}">محصولات</a><a href="{{ route('cart.index') }}">سبد خرید</a><a href="@auth{{ route('account.orders') }}@else{{ route('auth') }}@endauth">سفارش‌های من</a></div><div><h3>ارتباط با ما</h3><p>{{ $supportUrl ?: 'پشتیبانی آنلاین' }}</p></div></div><div class="home-wrap footer-bottom">© {{ now()->year }} {{ $siteName }}</div></footer>
</div>
<script>
(()=>{const r=document.querySelector('[data-home-banner]');if(!r)return;const s=[...r.querySelectorAll('[data-home-slide]')];if(s.length<2)return;let i=0,show=n=>s.forEach((x,j)=>x.style.display=j===n?'block':'none');r.querySelector('.hero-prev')?.addEventListener('click',()=>{i=(i+1)%s.length;show(i)});r.querySelector('.hero-next')?.addEventListener('click',()=>{i=(i-1+s.length)%s.length;show(i)});setInterval(()=>{i=(i+1)%s.length;show(i)},5000)})();
</script>
@endsection