@extends('layouts.store')

@section('content')
<style>
.products-page{background:#fff;color:#18212b;margin-inline:calc((100vw - min(1270px,calc(100% - 34px)))/-2);min-height:100vh}.products-wrap{width:min(1160px,calc(100% - 28px));margin:auto}
.products-top{padding:18px 0 10px;display:flex;align-items:center;justify-content:space-between;gap:15px}.products-top h1{margin:0;font-size:24px;font-weight:900}.products-top p{margin:5px 0 0;color:#8793a0;font-size:11px}.search{width:min(320px,100%);height:42px;border:1px solid #e1e7ed;border-radius:9px;padding:0 14px;outline:0}
.banner{height:210px;border-radius:8px;overflow:hidden;position:relative;background:#edf3f8;margin:8px 0 18px}.banner img{width:100%;height:100%;object-fit:cover}.banner-empty{height:100%;display:grid;place-items:center;color:#9aa6b2}.banner-nav{position:absolute;top:50%;transform:translateY(-50%);width:32px;height:32px;border:0;border-radius:50%;background:#fff;color:#657585;box-shadow:0 4px 15px #0002;cursor:pointer}.banner-prev{right:12px}.banner-next{left:12px}
.promo{display:grid;grid-template-columns:1fr repeat(5,minmax(120px,1fr));gap:8px;background:linear-gradient(135deg,#67142f,#a91746);padding:10px;border-radius:8px;margin-bottom:30px;color:#fff}.promo-copy{display:flex;flex-direction:column;justify-content:center;padding:8px 12px}.promo-copy strong{font-size:22px}.promo-copy span{font-size:10px;opacity:.85;margin-top:5px}.promo-card{background:#fff;border-radius:8px;padding:9px;color:#344454;min-width:0}.promo-card img{width:100%;height:85px;object-fit:contain;border-radius:6px;background:#f6f8fa}.promo-card b{display:block;font-size:11px;margin-top:7px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.promo-card small{font-size:9px;color:#8a98a5}
.category-block{margin:0 0 34px}.category-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:12px}.category-head h2{font-size:16px;margin:0;font-weight:900}.category-head a{font-size:10px;color:#377cf6}.category-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:9px}.product{background:#fff;border:1px solid #e7edf3;border-radius:9px;padding:10px;position:relative;transition:.2s}.product:hover{transform:translateY(-3px);box-shadow:0 12px 28px #20304012}.product-img{height:140px;border-radius:7px;background:#f4f7f9;display:grid;place-items:center;overflow:hidden}.product-img img{width:100%;height:100%;object-fit:contain}.product-placeholder{font-size:35px;color:#9ca9b5}.tag{position:absolute;top:14px;right:14px;background:#435cf2;color:#fff;font-size:7px;padding:3px 6px;border-radius:3px}.product h3{font-size:11px;margin:9px 0 4px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.product p{font-size:9px;color:#8a97a3;height:29px;line-height:1.6;margin:0;overflow:hidden}.price{font-size:10px;font-weight:900;margin-top:7px;color:#33485b}.buy{display:flex;justify-content:space-between;align-items:center;margin-top:8px}.buy span{font-size:9px;color:#9aa5af}.buy-button{background:#eef6ff;color:#1589dc;border-radius:7px;padding:5px 8px}
@media(max-width:900px){.promo{grid-template-columns:1fr repeat(3,1fr);overflow:auto}.promo-copy{min-width:180px}.category-grid{grid-template-columns:repeat(3,1fr)}}@media(max-width:600px){.products-top{flex-direction:column;align-items:stretch}.search{width:100%}.banner{height:135px}.promo{grid-template-columns:170px repeat(5,140px);overflow:auto}.category-grid{grid-template-columns:repeat(2,1fr)}.product-img{height:120px}}
</style>
<div class="products-page"><div class="products-wrap">
<div class="products-top"><div><h1>محصولات و خدمات</h1><p>محصول موردنظرت را انتخاب کن و مستقیماً وارد صفحه خرید شو.</p></div><form method="GET" action="{{ route('products.index') }}"><input class="search" name="q" value="{{ request('q') }}" placeholder="جستجو در محصولات و خدمات..."></form></div>
<div class="banner" data-banner>
@if($bannerSlides->isNotEmpty()) @foreach($bannerSlides as $i=>$slide)<a href="{{ $slide['link'] ?? '#' }}" data-banner-slide style="display:{{ $i===0?'block':'none' }};width:100%;height:100%"><img src="{{ $slide['image'] }}" alt="بنر فروشگاه"></a>@endforeach @if($bannerSlides->count()>1)<button class="banner-nav banner-prev" type="button">›</button><button class="banner-nav banner-next" type="button">‹</button>@endif
@else<div class="banner-empty">برای نمایش بنر، از تنظیمات فروشگاه یک اسلاید اضافه کن.</div>@endif
</div>
<div class="promo"><div class="promo-copy"><strong>⚡ پیشنهاد ویژه</strong><span>محصولات محبوب با قیمت مناسب</span></div>@foreach($products->take(5) as $product)<a class="promo-card" href="{{ route('product.show',$product) }}"><div><img src="{{ $product->image ?: '' }}" alt="{{ $product->name }}"></div><b>{{ $product->name }}</b><small>{{ number_format($product->price) }} {{ $product->currency === 'IRR' ? 'ریال' : $product->currency }}</small></a>@endforeach</div>
@php($groups=$products->groupBy(fn($p)=>$p->category?->name ?: 'سایر محصولات'))
@if($groups->isEmpty())<div style="padding:70px;text-align:center;color:#8b98a5">هنوز محصولی برای نمایش ثبت نشده است.</div>
@else @foreach($groups as $name=>$items)<section class="category-block"><div class="category-head"><h2>{{ $name }}</h2><a href="{{ route('products.index',['category'=>$items->first()->category?->slug]) }}">مشاهده همه ←</a></div><div class="category-grid">@foreach($items->take(5) as $product)<a class="product" href="{{ route('product.show',$product) }}"><span class="tag">ویژه</span><div class="product-img">@if($product->image)<img src="{{ $product->image }}" alt="{{ $product->name }}" loading="lazy">@else<div class="product-placeholder">✦</div>@endif</div><h3>{{ $product->name }}</h3><p>{{ $product->description ?: 'محصول دیجیتال با تحویل سریع و پشتیبانی.' }}</p><div class="price">{{ number_format($product->price) }} {{ $product->currency === 'IRR' ? 'ریال' : $product->currency }}</div><div class="buy"><span>مشاهده جزئیات</span><span class="buy-button">🛒</span></div></a>@endforeach</div></section>@endforeach @endif
</div></div>
<script>(()=>{const r=document.querySelector('[data-banner]');if(!r)return;const s=[...r.querySelectorAll('[data-banner-slide]')];if(s.length<2)return;let i=0,show=n=>s.forEach((x,j)=>x.style.display=j===n?'block':'none');r.querySelector('.banner-prev')?.addEventListener('click',()=>{i=(i+1)%s.length;show(i)});r.querySelector('.banner-next')?.addEventListener('click',()=>{i=(i-1+s.length)%s.length;show(i)});setInterval(()=>{i=(i+1)%s.length;show(i)},5000)})();</script>
@endsection